### ISSUE TITLE
服务端是如何代理图源链接的？

### ISSUE THREAD

**Issue by owen800q** [cheer-fun/pixivic-web-backend#1]
谢谢老哥，这个项目十分适合刚学Spring的新手阅读，代码非常简洁
有个问题不解
服务端直接返回的Json结果是源P站Cdn存放图片链接
```
imageUrls": [
{
"squareMedium": "https://i.pximg.net/c/540x540_10_webp/img-master/img/2018/01/06/20/06/28/66674174_p0_square1200.jpg",
"medium": "https://i.pximg.net/c/540x540_70/img-master/img/2018/01/06/20/06/28/66674174_p0_master1200.jpg",
"large": "https://i.pximg.net/c/600x1200_90_webp/img-master/img/2018/01/06/20/06/28/66674174_p0_master1200.jpg",
"original": "https://i.pximg.net/img-original/img/2018/01/06/20/06/28/66674174_p0.png"
}
],
```

前端 拼接了个Prefix
![image](https://user-images.githubusercontent.com/19252045/73131343-494da300-4044-11ea-8855-bb045ced145f.png)

实际渲染地址成了
https://bigimg.cheerfun.dev/get/https://i.pximg.net/img-original/img/2017/10/01/09/54/13/65216548_p0.png

bigimg.cheerfun.dev 请问是如何转发到P站的地址的？ 

我用nginx设置反向代理返回的是403

**Comment by owen800q** [comment]
@OysterQAQ

**Comment by owen800q** [comment]
@collabH @challenger97

**Comment by collabH** [comment]
我帮你叫下 @OysterQAQ

**Comment by OysterQAQ** [comment]
需要在反向代理的过程中增加一个请求头，Referer:https://app-api.pixiv.net，p站做了referer验证来防盗链
